{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "de174b3f-a102-45c1-a505-88ef4d739edb",
   "metadata": {},
   "outputs": [],
   "source": [
    "#%%\n",
    "import os\n",
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "#%%\n",
    "imgSize = 128\n",
    "\n",
    "def loadImage(directory):\n",
    "    images, labels = [], []\n",
    "    for label, folder in enumerate(['Melanoma', 'NotMelanoma']):\n",
    "        path = os.path.join(directory, folder)\n",
    "        for name in os.listdir(path):\n",
    "            imgPath = os.path.join(path, name)\n",
    "            img = cv2.imread(imgPath)\n",
    "            if img is None:\n",
    "                continue\n",
    "            img = cv2.resize(img, (imgSize, imgSize))\n",
    "            images.append(img)\n",
    "            labels.append(label)\n",
    "    return np.array(images), np.array(labels)\n",
    "xTrain, yTrain = loadImage('train_sep')\n",
    "xValid, yValid = loadImage('valid')\n",
    "xTest, yTest = loadImage('test')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "aa57d1ce-9aac-4cf8-a2ac-6ad2b7bb97a2",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-02 20:53:33.826491: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1733190813.843171 1690061 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1733190813.848245 1690061 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2024-12-02 20:53:33.867316: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 2.0.2\n",
      "  warnings.warn(f\"A NumPy version >={np_minversion} and <{np_maxversion}\"\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 473, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 462, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 369, in dispatch_shell\n",
      "    await result\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 664, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 355, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2854, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2900, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3301, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1690061/3173243336.py\", line 1, in <cell line: 1>\n",
      "    import tensorflow as tf\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/__init__.py\", line 49, in <module>\n",
      "    from tensorflow._api.v2 import __internal__\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/__init__.py\", line 13, in <module>\n",
      "    from tensorflow._api.v2.__internal__ import feature_column\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/feature_column/__init__.py\", line 8, in <module>\n",
      "    from tensorflow.python.feature_column.feature_column_v2 import DenseColumn # line: 1777\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column_v2.py\", line 38, in <module>\n",
      "    from tensorflow.python.feature_column import feature_column as fc_old\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column.py\", line 41, in <module>\n",
      "    from tensorflow.python.layers import base\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/layers/base.py\", line 16, in <module>\n",
      "    from tensorflow.python.keras.legacy_tf_layers import base\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/keras/__init__.py\", line 25, in <module>\n",
      "    from tensorflow.python.keras import models\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/keras/models.py\", line 25, in <module>\n",
      "    from tensorflow.python.keras.engine import training_v1\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training_v1.py\", line 46, in <module>\n",
      "    from tensorflow.python.keras.engine import training_arrays_v1\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py\", line 37, in <module>\n",
      "    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/scipy/sparse/__init__.py\", line 228, in <module>\n",
      "    from .csr import *\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/scipy/sparse/csr.py\", line 10, in <module>\n",
      "    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1979, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1981, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "AttributeError: _ARRAY_API not found\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 473, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 462, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 369, in dispatch_shell\n",
      "    await result\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 664, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 355, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2854, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2900, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3301, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1690061/3173243336.py\", line 1, in <cell line: 1>\n",
      "    import tensorflow as tf\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/__init__.py\", line 49, in <module>\n",
      "    from tensorflow._api.v2 import __internal__\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/__init__.py\", line 13, in <module>\n",
      "    from tensorflow._api.v2.__internal__ import feature_column\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/_api/v2/__internal__/feature_column/__init__.py\", line 8, in <module>\n",
      "    from tensorflow.python.feature_column.feature_column_v2 import DenseColumn # line: 1777\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column_v2.py\", line 38, in <module>\n",
      "    from tensorflow.python.feature_column import feature_column as fc_old\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/feature_column/feature_column.py\", line 41, in <module>\n",
      "    from tensorflow.python.layers import base\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/layers/base.py\", line 16, in <module>\n",
      "    from tensorflow.python.keras.legacy_tf_layers import base\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/keras/__init__.py\", line 25, in <module>\n",
      "    from tensorflow.python.keras import models\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/keras/models.py\", line 25, in <module>\n",
      "    from tensorflow.python.keras.engine import training_v1\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training_v1.py\", line 71, in <module>\n",
      "    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/scipy/sparse/__init__.py\", line 228, in <module>\n",
      "    from .csr import *\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/scipy/sparse/csr.py\", line 10, in <module>\n",
      "    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1979, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1981, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "AttributeError: _ARRAY_API not found\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 473, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 462, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 369, in dispatch_shell\n",
      "    await result\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 664, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 355, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2854, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2900, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3301, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1690061/3173243336.py\", line 1, in <cell line: 1>\n",
      "    import tensorflow as tf\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/__init__.py\", line 467, in <module>\n",
      "    importlib.import_module(\"keras.src.optimizers\")\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/__init__.py\", line 2, in <module>\n",
      "    from keras.api import DTypePolicy\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/api/__init__.py\", line 8, in <module>\n",
      "    from keras.api import activations\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/api/activations/__init__.py\", line 7, in <module>\n",
      "    from keras.src.activations import deserialize\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/__init__.py\", line 1, in <module>\n",
      "    from keras.src import activations\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/activations/__init__.py\", line 30, in <module>\n",
      "    from keras.src.saving import object_registration\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/saving/__init__.py\", line 7, in <module>\n",
      "    from keras.src.saving.saving_api import load_model\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/saving/saving_api.py\", line 7, in <module>\n",
      "    from keras.src.legacy.saving import legacy_h5_format\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/legacy/saving/legacy_h5_format.py\", line 13, in <module>\n",
      "    from keras.src.legacy.saving import saving_utils\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/legacy/saving/saving_utils.py\", line 10, in <module>\n",
      "    from keras.src import models\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/models/__init__.py\", line 1, in <module>\n",
      "    from keras.src.models.functional import Functional\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 16, in <module>\n",
      "    from keras.src.models.model import Model\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/models/model.py\", line 12, in <module>\n",
      "    from keras.src.trainers import trainer as base_trainer\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/trainers/trainer.py\", line 14, in <module>\n",
      "    from keras.src.trainers.data_adapters import data_adapter_utils\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/__init__.py\", line 4, in <module>\n",
      "    from keras.src.trainers.data_adapters import array_data_adapter\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/array_data_adapter.py\", line 7, in <module>\n",
      "    from keras.src.trainers.data_adapters import array_slicing\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/array_slicing.py\", line 12, in <module>\n",
      "    import pandas\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py\", line 50, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/ops/__init__.py\", line 8, in <module>\n",
      "    from pandas.core.ops.array_ops import (\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py\", line 56, in <module>\n",
      "    from pandas.core.computation import expressions\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py\", line 21, in <module>\n",
      "    from pandas.core.computation.check import NUMEXPR_INSTALLED\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/computation/check.py\", line 5, in <module>\n",
      "    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/compat/_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/numexpr/__init__.py\", line 26, in <module>\n",
      "    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1979, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1981, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "AttributeError: _ARRAY_API not found\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 473, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 462, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 369, in dispatch_shell\n",
      "    await result\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 664, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 355, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2854, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2900, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3301, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1690061/3173243336.py\", line 1, in <cell line: 1>\n",
      "    import tensorflow as tf\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/__init__.py\", line 467, in <module>\n",
      "    importlib.import_module(\"keras.src.optimizers\")\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/__init__.py\", line 2, in <module>\n",
      "    from keras.api import DTypePolicy\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/api/__init__.py\", line 8, in <module>\n",
      "    from keras.api import activations\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/api/activations/__init__.py\", line 7, in <module>\n",
      "    from keras.src.activations import deserialize\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/__init__.py\", line 1, in <module>\n",
      "    from keras.src import activations\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/activations/__init__.py\", line 30, in <module>\n",
      "    from keras.src.saving import object_registration\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/saving/__init__.py\", line 7, in <module>\n",
      "    from keras.src.saving.saving_api import load_model\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/saving/saving_api.py\", line 7, in <module>\n",
      "    from keras.src.legacy.saving import legacy_h5_format\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/legacy/saving/legacy_h5_format.py\", line 13, in <module>\n",
      "    from keras.src.legacy.saving import saving_utils\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/legacy/saving/saving_utils.py\", line 10, in <module>\n",
      "    from keras.src import models\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/models/__init__.py\", line 1, in <module>\n",
      "    from keras.src.models.functional import Functional\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/models/functional.py\", line 16, in <module>\n",
      "    from keras.src.models.model import Model\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/models/model.py\", line 12, in <module>\n",
      "    from keras.src.trainers import trainer as base_trainer\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/trainers/trainer.py\", line 14, in <module>\n",
      "    from keras.src.trainers.data_adapters import data_adapter_utils\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/__init__.py\", line 4, in <module>\n",
      "    from keras.src.trainers.data_adapters import array_data_adapter\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/array_data_adapter.py\", line 7, in <module>\n",
      "    from keras.src.trainers.data_adapters import array_slicing\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/trainers/data_adapters/array_slicing.py\", line 12, in <module>\n",
      "    import pandas\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/api.py\", line 28, in <module>\n",
      "    from pandas.core.arrays import Categorical\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.arrays.arrow import ArrowExtensionArray\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/__init__.py\", line 5, in <module>\n",
      "    from pandas.core.arrays.arrow.array import ArrowExtensionArray\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py\", line 64, in <module>\n",
      "    from pandas.core.arrays.masked import BaseMaskedArray\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py\", line 60, in <module>\n",
      "    from pandas.core import (\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/core/nanops.py\", line 52, in <module>\n",
      "    bn = import_optional_dependency(\"bottleneck\", errors=\"warn\")\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/pandas/compat/_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/bottleneck/__init__.py\", line 2, in <module>\n",
      "    from .reduce import (\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1979, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1981, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "AttributeError: _ARRAY_API not found\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 473, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 462, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 369, in dispatch_shell\n",
      "    await result\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 664, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 355, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2854, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2900, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3301, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1690061/3173243336.py\", line 1, in <cell line: 1>\n",
      "    import tensorflow as tf\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/__init__.py\", line 467, in <module>\n",
      "    importlib.import_module(\"keras.src.optimizers\")\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/__init__.py\", line 2, in <module>\n",
      "    from keras.api import DTypePolicy\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/api/__init__.py\", line 8, in <module>\n",
      "    from keras.api import activations\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/api/activations/__init__.py\", line 7, in <module>\n",
      "    from keras.src.activations import deserialize\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/__init__.py\", line 13, in <module>\n",
      "    from keras.src import visualization\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/visualization/__init__.py\", line 2, in <module>\n",
      "    from keras.src.visualization import plot_image_gallery\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/visualization/plot_image_gallery.py\", line 13, in <module>\n",
      "    import matplotlib.pyplot as plt\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/__init__.py\", line 109, in <module>\n",
      "    from . import _api, _version, cbook, docstring, rcsetup\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/rcsetup.py\", line 27, in <module>\n",
      "    from matplotlib.colors import Colormap, is_color_like\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/colors.py\", line 56, in <module>\n",
      "    from matplotlib import _api, cbook, scale\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/scale.py\", line 23, in <module>\n",
      "    from matplotlib.ticker import (\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/ticker.py\", line 136, in <module>\n",
      "    from matplotlib import transforms as mtransforms\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/transforms.py\", line 46, in <module>\n",
      "    from matplotlib._path import (\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1979, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1981, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "AttributeError: _ARRAY_API not found\n",
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.0.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 600, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/base_events.py\", line 1896, in _run_once\n",
      "    handle._run()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 473, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 462, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 369, in dispatch_shell\n",
      "    await result\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 664, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 355, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2854, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2900, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3301, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1690061/3173243336.py\", line 1, in <cell line: 1>\n",
      "    import tensorflow as tf\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/tensorflow/__init__.py\", line 467, in <module>\n",
      "    importlib.import_module(\"keras.src.optimizers\")\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/__init__.py\", line 2, in <module>\n",
      "    from keras.api import DTypePolicy\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/api/__init__.py\", line 34, in <module>\n",
      "    from keras.api import visualization\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/api/visualization/__init__.py\", line 11, in <module>\n",
      "    from keras.src.visualization.plot_bounding_box_gallery import (\n",
      "  File \"/storage/home/gjs5555/.local/lib/python3.10/site-packages/keras/src/visualization/plot_bounding_box_gallery.py\", line 12, in <module>\n",
      "    from matplotlib import patches  # For legend patches\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/__init__.py\", line 109, in <module>\n",
      "    from . import _api, _version, cbook, docstring, rcsetup\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/rcsetup.py\", line 27, in <module>\n",
      "    from matplotlib.colors import Colormap, is_color_like\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/colors.py\", line 56, in <module>\n",
      "    from matplotlib import _api, cbook, scale\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/scale.py\", line 23, in <module>\n",
      "    from matplotlib.ticker import (\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/ticker.py\", line 136, in <module>\n",
      "    from matplotlib import transforms as mtransforms\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/transforms.py\", line 46, in <module>\n",
      "    from matplotlib._path import (\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1979, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'AttributeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 1981, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(etype,\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1105, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 999, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 851, in structured_traceback\n",
      "    assert etb is not None\n",
      "AssertionError\n",
      "\n",
      "Original exception was:\n",
      "AttributeError: _ARRAY_API not found\n",
      "I0000 00:00:1733190820.407554 1690061 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 11072 MB memory:  -> device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:03:00.0, compute capability: 6.0\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-weight: bold\">Model: \"sequential\"</span>\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[1mModel: \"sequential\"\u001b[0m\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\">┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓\n",
       "┃<span style=\"font-weight: bold\"> Layer (type)                    </span>┃<span style=\"font-weight: bold\"> Output Shape           </span>┃<span style=\"font-weight: bold\">       Param # </span>┃\n",
       "┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩\n",
       "│ efficientnetb0 (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">Functional</span>)     │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">4</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">4</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">1280</span>)     │     <span style=\"color: #00af00; text-decoration-color: #00af00\">4,049,571</span> │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ global_average_pooling2d        │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">1280</span>)           │             <span style=\"color: #00af00; text-decoration-color: #00af00\">0</span> │\n",
       "│ (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">GlobalAveragePooling2D</span>)        │                        │               │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dense (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">Dense</span>)                   │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">128</span>)            │       <span style=\"color: #00af00; text-decoration-color: #00af00\">163,968</span> │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dropout (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">Dropout</span>)               │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">128</span>)            │             <span style=\"color: #00af00; text-decoration-color: #00af00\">0</span> │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dense_1 (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">Dense</span>)                 │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">1</span>)              │           <span style=\"color: #00af00; text-decoration-color: #00af00\">129</span> │\n",
       "└─────────────────────────────────┴────────────────────────┴───────────────┘\n",
       "</pre>\n"
      ],
      "text/plain": [
       "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓\n",
       "┃\u001b[1m \u001b[0m\u001b[1mLayer (type)                   \u001b[0m\u001b[1m \u001b[0m┃\u001b[1m \u001b[0m\u001b[1mOutput Shape          \u001b[0m\u001b[1m \u001b[0m┃\u001b[1m \u001b[0m\u001b[1m      Param #\u001b[0m\u001b[1m \u001b[0m┃\n",
       "┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩\n",
       "│ efficientnetb0 (\u001b[38;5;33mFunctional\u001b[0m)     │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m4\u001b[0m, \u001b[38;5;34m4\u001b[0m, \u001b[38;5;34m1280\u001b[0m)     │     \u001b[38;5;34m4,049,571\u001b[0m │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ global_average_pooling2d        │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m1280\u001b[0m)           │             \u001b[38;5;34m0\u001b[0m │\n",
       "│ (\u001b[38;5;33mGlobalAveragePooling2D\u001b[0m)        │                        │               │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dense (\u001b[38;5;33mDense\u001b[0m)                   │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m128\u001b[0m)            │       \u001b[38;5;34m163,968\u001b[0m │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dropout (\u001b[38;5;33mDropout\u001b[0m)               │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m128\u001b[0m)            │             \u001b[38;5;34m0\u001b[0m │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dense_1 (\u001b[38;5;33mDense\u001b[0m)                 │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m1\u001b[0m)              │           \u001b[38;5;34m129\u001b[0m │\n",
       "└─────────────────────────────────┴────────────────────────┴───────────────┘\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-weight: bold\"> Total params: </span><span style=\"color: #00af00; text-decoration-color: #00af00\">4,213,668</span> (16.07 MB)\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[1m Total params: \u001b[0m\u001b[38;5;34m4,213,668\u001b[0m (16.07 MB)\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-weight: bold\"> Trainable params: </span><span style=\"color: #00af00; text-decoration-color: #00af00\">164,097</span> (641.00 KB)\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[1m Trainable params: \u001b[0m\u001b[38;5;34m164,097\u001b[0m (641.00 KB)\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-weight: bold\"> Non-trainable params: </span><span style=\"color: #00af00; text-decoration-color: #00af00\">4,049,571</span> (15.45 MB)\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[1m Non-trainable params: \u001b[0m\u001b[38;5;34m4,049,571\u001b[0m (15.45 MB)\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "from tensorflow.keras import layers, models\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "from tensorflow.keras.applications import EfficientNetB0\n",
    "\n",
    "base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(imgSize, imgSize, 3))\n",
    "base_model.trainable = False\n",
    "\n",
    "model = models.Sequential([\n",
    "    base_model,\n",
    "    layers.GlobalAveragePooling2D(),\n",
    "    layers.Dense(128, activation='relu'),\n",
    "    layers.Dropout(0.5),\n",
    "    layers.Dense(1, activation='sigmoid')\n",
    "])\n",
    "model.compile(optimizer='adam',\n",
    "              loss='binary_crossentropy',\n",
    "              metrics=['accuracy'])\n",
    "\n",
    "model.summary()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a869875f-becb-4b00-ade7-3884d3c544af",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "I0000 00:00:1733190833.003083 1690440 service.cc:148] XLA service 0x147ea0002d00 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n",
      "I0000 00:00:1733190833.003811 1690440 service.cc:156]   StreamExecutor device (0): Tesla P100-PCIE-12GB, Compute Capability 6.0\n",
      "2024-12-02 20:53:53.293461: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.\n",
      "I0000 00:00:1733190834.825617 1690440 cuda_dnn.cc:529] Loaded cuDNN version 90300\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m 11/668\u001b[0m \u001b[37m━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[1m7s\u001b[0m 11ms/step - accuracy: 0.5373 - loss: 0.6854   "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I0000 00:00:1733190842.725140 1690440 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m43s\u001b[0m 37ms/step - accuracy: 0.8380 - loss: 0.3598 - val_accuracy: 0.9130 - val_loss: 0.2244\n",
      "Epoch 2/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9038 - loss: 0.2354 - val_accuracy: 0.9175 - val_loss: 0.2059\n",
      "Epoch 3/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9133 - loss: 0.2114 - val_accuracy: 0.9194 - val_loss: 0.2000\n",
      "Epoch 4/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m10s\u001b[0m 12ms/step - accuracy: 0.9185 - loss: 0.1996 - val_accuracy: 0.9236 - val_loss: 0.1916\n",
      "Epoch 5/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9252 - loss: 0.1893 - val_accuracy: 0.9175 - val_loss: 0.1965\n",
      "Epoch 6/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9236 - loss: 0.1786 - val_accuracy: 0.9222 - val_loss: 0.1928\n",
      "Epoch 7/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m9s\u001b[0m 13ms/step - accuracy: 0.9362 - loss: 0.1604 - val_accuracy: 0.9099 - val_loss: 0.2132\n",
      "Epoch 8/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9289 - loss: 0.1647 - val_accuracy: 0.9267 - val_loss: 0.1893\n",
      "Epoch 9/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m11s\u001b[0m 13ms/step - accuracy: 0.9357 - loss: 0.1563 - val_accuracy: 0.9248 - val_loss: 0.1854\n",
      "Epoch 10/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9369 - loss: 0.1581 - val_accuracy: 0.9206 - val_loss: 0.1913\n",
      "Epoch 11/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9422 - loss: 0.1466 - val_accuracy: 0.9276 - val_loss: 0.1863\n",
      "Epoch 12/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9424 - loss: 0.1452 - val_accuracy: 0.9250 - val_loss: 0.1893\n",
      "Epoch 13/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9471 - loss: 0.1323 - val_accuracy: 0.9276 - val_loss: 0.1871\n",
      "Epoch 14/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9462 - loss: 0.1375 - val_accuracy: 0.9323 - val_loss: 0.1872\n",
      "Epoch 15/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m9s\u001b[0m 13ms/step - accuracy: 0.9400 - loss: 0.1396 - val_accuracy: 0.9298 - val_loss: 0.1918\n",
      "Epoch 16/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m10s\u001b[0m 12ms/step - accuracy: 0.9510 - loss: 0.1267 - val_accuracy: 0.9315 - val_loss: 0.1971\n",
      "Epoch 17/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9465 - loss: 0.1295 - val_accuracy: 0.9259 - val_loss: 0.1938\n",
      "Epoch 18/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9448 - loss: 0.1317 - val_accuracy: 0.9298 - val_loss: 0.1936\n",
      "Epoch 19/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m8s\u001b[0m 12ms/step - accuracy: 0.9496 - loss: 0.1238 - val_accuracy: 0.9323 - val_loss: 0.1945\n",
      "Epoch 20/20\n",
      "\u001b[1m668/668\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m9s\u001b[0m 13ms/step - accuracy: 0.9499 - loss: 0.1216 - val_accuracy: 0.9301 - val_loss: 0.1996\n"
     ]
    }
   ],
   "source": [
    "history = model.fit(xTrain, yTrain, epochs=20, \n",
    "                    validation_data=(xValid, yValid), \n",
    "                    batch_size=16)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "155a9f65-ca9e-4512-9eaf-04ca489aa9be",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "module 'matplotlib' has no attribute 'get_data_path'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Input \u001b[0;32mIn [7]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmatplotlib\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpyplot\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mplt\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;66;03m# Plot training & validation accuracy\u001b[39;00m\n\u001b[1;32m      4\u001b[0m plt\u001b[38;5;241m.\u001b[39mplot(history\u001b[38;5;241m.\u001b[39mhistory[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124maccuracy\u001b[39m\u001b[38;5;124m'\u001b[39m], label\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtrain_accuracy\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "File \u001b[0;32m/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/__init__.py:877\u001b[0m, in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m    870\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m config\n\u001b[1;32m    873\u001b[0m \u001b[38;5;66;03m# When constructing the global instances, we need to perform certain updates\u001b[39;00m\n\u001b[1;32m    874\u001b[0m \u001b[38;5;66;03m# by explicitly calling the superclass (dict.update, dict.items) to avoid\u001b[39;00m\n\u001b[1;32m    875\u001b[0m \u001b[38;5;66;03m# triggering resolution of _auto_backend_sentinel.\u001b[39;00m\n\u001b[1;32m    876\u001b[0m rcParamsDefault \u001b[38;5;241m=\u001b[39m _rc_params_in_file(\n\u001b[0;32m--> 877\u001b[0m     \u001b[43mcbook\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_get_data_path\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmatplotlibrc\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m,\n\u001b[1;32m    878\u001b[0m     \u001b[38;5;66;03m# Strip leading comment.\u001b[39;00m\n\u001b[1;32m    879\u001b[0m     transform\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mlambda\u001b[39;00m line: line[\u001b[38;5;241m1\u001b[39m:] \u001b[38;5;28;01mif\u001b[39;00m line\u001b[38;5;241m.\u001b[39mstartswith(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m#\u001b[39m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;28;01melse\u001b[39;00m line,\n\u001b[1;32m    880\u001b[0m     fail_on_error\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m)\n\u001b[1;32m    881\u001b[0m \u001b[38;5;28mdict\u001b[39m\u001b[38;5;241m.\u001b[39mupdate(rcParamsDefault, rcsetup\u001b[38;5;241m.\u001b[39m_hardcoded_defaults)\n\u001b[1;32m    882\u001b[0m \u001b[38;5;66;03m# Normally, the default matplotlibrc file contains *no* entry for backend (the\u001b[39;00m\n\u001b[1;32m    883\u001b[0m \u001b[38;5;66;03m# corresponding line starts with ##, not #; we fill on _auto_backend_sentinel\u001b[39;00m\n\u001b[1;32m    884\u001b[0m \u001b[38;5;66;03m# in that case.  However, packagers can set a different default backend\u001b[39;00m\n\u001b[1;32m    885\u001b[0m \u001b[38;5;66;03m# (resulting in a normal `#backend: foo` line) in which case we should *not*\u001b[39;00m\n\u001b[1;32m    886\u001b[0m \u001b[38;5;66;03m# fill in _auto_backend_sentinel.\u001b[39;00m\n",
      "File \u001b[0;32m/storage/icds/RISE/sw8/anaconda/conda_envs/tensorflow/lib/python3.10/site-packages/matplotlib/cbook/__init__.py:518\u001b[0m, in \u001b[0;36m_get_data_path\u001b[0;34m(*args)\u001b[0m\n\u001b[1;32m    512\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_get_data_path\u001b[39m(\u001b[38;5;241m*\u001b[39margs):\n\u001b[1;32m    513\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m    514\u001b[0m \u001b[38;5;124;03m    Return the `pathlib.Path` to a resource file provided by Matplotlib.\u001b[39;00m\n\u001b[1;32m    515\u001b[0m \n\u001b[1;32m    516\u001b[0m \u001b[38;5;124;03m    ``*args`` specify a path relative to the base data path.\u001b[39;00m\n\u001b[1;32m    517\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 518\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m Path(\u001b[43mmatplotlib\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_data_path\u001b[49m(), \u001b[38;5;241m*\u001b[39margs)\n",
      "\u001b[0;31mAttributeError\u001b[0m: module 'matplotlib' has no attribute 'get_data_path'"
     ]
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Plot training & validation accuracy\n",
    "plt.plot(history.history['accuracy'], label='train_accuracy')\n",
    "plt.plot(history.history['val_accuracy'], label='val_accuracy')\n",
    "plt.xlabel('Epochs')\n",
    "plt.ylabel('Accuracy')\n",
    "plt.legend()\n",
    "plt.show()\n",
    "\n",
    "# Plot training & validation loss\n",
    "plt.plot(history.history['loss'], label='train_loss')\n",
    "plt.plot(history.history['val_loss'], label='val_loss')\n",
    "plt.xlabel('Epochs')\n",
    "plt.ylabel('Loss')\n",
    "plt.legend()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f7b1ef12-2f1e-4dad-ae48-92f41533e0a1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m112/112\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m9s\u001b[0m 47ms/step - accuracy: 0.9461 - loss: 0.1360\n",
      "Test Accuracy: 0.92\n"
     ]
    }
   ],
   "source": [
    "test_loss, test_acc = model.evaluate(xTest, yTest)\n",
    "print(f\"Test Accuracy: {test_acc:.2f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "15338d01-2c9a-4f7b-a42f-893c4b801eb9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:The `save_format` argument is deprecated in Keras 3. We recommend removing this argument as it can be inferred from the file path. Received: save_format=keras_v3\n"
     ]
    }
   ],
   "source": [
    "model.save('MelanomaModel.keras', save_format='keras_v3')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e2f04ce-2c50-4d76-bdb0-110450a03724",
   "metadata": {},
   "outputs": [],
   "source": [
    "import keras\n",
    "import tensorflow as tf\n",
    "print(tf.__version__)\n",
    "print(keras.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b23e4540-f5ec-45a5-826d-9c6909922f4b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b0062a92-799f-4f2e-bddd-a1a64087f2c4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28353d28-c592-4bbc-93ec-3df6cd8fdbc2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
